trigger:
- none

pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: MemcachedDeployment
  displayName: MemcachedDeployment
  jobs:
  - job: HelmRepoAdd
    displayName: HelmRepoAdd
    steps:
    - checkout: none
    - task: CmdLine@2
      inputs:
        script: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
  - deployment: MemcachedDeployment
    displayName: MemcachedDeployment
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: HelmDeploy@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Azure DevOps Service Connection'
              azureResourceGroup: 'aks-rg'
              kubernetesCluster: 'aks-cluster'
              namespace: 'memcached'
              command: 'upgrade'
              chartType: 'Name'
              chartName: 'bitnami/memcached'
              chartVersion: '7.0.0'
              releaseName: 'memcached'
              overrideValues: 'replicaCount=2,persistence.enabled=true,persistence.size=1Gi,containerPorts.memcached=11211,architecture=high-availability,service.clusterIP=None,service.ports.memcached=11211'
          
       
  
